function button(){
    s1.mousePressed(()=>{
        e1.hide();
        a1.hide();
        s1.hide();
        e2.show();
        a2.show();
        s2.show();
        q1=e1.value();
        w1=a1.value();
        number=number+1
    });
    s2.mousePressed(()=>{
        e2.hide();
        a2.hide();
        s2.hide();
        e3.show();
        a3.show();
        s3.show();
        q2=e2.value();
        w2=a2.value();
        number=number+1
    });
    s3.mousePressed(()=>{
        e3.hide();
        a3.hide();
        s3.hide();
        e4.show();
        a4.show();
        s4.show();
        q3=e3.value();
        w3=a3.value();
        number=number+1
    });
    s4.mousePressed(()=>{
        e4.hide();
        a4.hide();
        s4.hide();
        e5.show();
        a5.show();
        s5.show();
        q4=e4.value();
        w4=a4.value();
        number=number+1
    });
    s5.mousePressed(()=>{
        e5.hide();
        a5.hide();
        s5.hide();
        e6.show();
        a6.show();
        s6.show();
        q5=e5.value();
        w5=a5.value();
        number=number+1
    });
    s6.mousePressed(()=>{
        e6.hide();
        a6.hide();
        s6.hide();
        e7.show();
        a7.show();
        s7.show();
        q6=e6.value();
        w6=a6.value();
        number=number+1
    });
    s7.mousePressed(()=>{
        e7.hide();
        a7.hide();
        s7.hide();
        e8.show();
        a8.show();
        s8.show();
        q7=e7.value();
        w7=a7.value();
        number=number+1
    });
    s8.mousePressed(()=>{
        e8.hide();
        a8.hide();
        s8.hide();
        e9.show();
        a9.show();
        s9.show();
        q8=e8.value();
        w8=a8.value();
        number=number+1
    });
    s9.mousePressed(()=>{
        e9.hide();
        a9.hide();
        s9.hide();
        e10.show();
        a10.show();
        s10.show();
        q9=e9.value();
        w9=a9.value();
        number=number+1
    });
    s10.mousePressed(()=>{
        e10.hide();
        a10.hide();
        s10.hide();
        e11.show();
        a11.show();
        s11.show();
        q10=e10.value();
        w10=a10.value();
        number=number+1
    });
    s11.mousePressed(()=>{
        e11.hide();
        a11.hide();
        s11.hide();
        e12.show();
        a12.show();
        s12.show();
        q11=e11.value();
        w11=a11.value();
        number=number+1
    });
    s12.mousePressed(()=>{
        e12.hide();
        a12.hide();
        s12.hide();
        e13.show();
        a13.show();
        s13.show();
        q12=e12.value();
        w12=a12.value();
        number=number+1
    });
    s13.mousePressed(()=>{
        e13.hide();
        a13.hide();
        s13.hide();
        e14.show();
        a14.show();
        s14.show();
        q13=e13.value();
        w13=a13.value();
        number=number+1
    });
    s14.mousePressed(()=>{
        e14.hide();
        a14.hide();
        s14.hide();
        e15.show();
        a15.show();
        s15.show();
        q14=e14.value();
        w14=a14.value();
        number=number+1
    });
    s15.mousePressed(()=>{
        e15.hide();
        a15.hide();
        s15.hide();
        e16.show();
        a16.show();
        s16.show();
        q15=e15.value();
        w15=a15.value();
        number=number+1
    });
    s16.mousePressed(()=>{
        e16.hide();
        a16.hide();
        s16.hide();
        e17.show();
        a17.show();
        s17.show();
        q16=e16.value();
        w16=a16.value();
        number=number+1
    });
    s17.mousePressed(()=>{
        e17.hide();
        a17.hide();
        s17.hide();
        e18.show();
        a18.show();
        s18.show();
        q17=e17.value();
        w17=a17.value();
        number=number+1
    });
    s18.mousePressed(()=>{
        e18.hide();
        a18.hide();
        s18.hide();
        e19.show();
        a19.show();
        s19.show();
        q18=e18.value();
        w18=a18.value();
        number=number+1
    });
    s19.mousePressed(()=>{
        e19.hide();
        a19.hide();
        s19.hide();
        e20.show();
        a20.show();
        s20.show();
        q19=e19.value();
        w19=a19.value();
        number=number+1
    });
    s20.mousePressed(()=>{
        e20.hide();
        a20.hide();
        s20.hide();
        //e11.show();
        //a11.show();
        //s11.show();
        q20=e20.value();
        w20=a20.value();
        number=number+1
        gameState=1
    });

}